name: Accessabar Test (Ava)

on: [push]

jobs:
  build:
    name: Ava Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2-beta
      - name: Install deps
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: Test
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: ava
